import { ArrowDown, ArrowUpRight } from 'lucide-react';
import { Link } from 'react-router-dom';
import Seo from '../../components/Seo';
import { contact, experience } from '../../content/portfolio';

const courses = [
  { name: 'AWS Cloud Technical Essentials', issuer: 'AWS · 2024', href: 'https://coursera.org/verify/RV5DTN9SE2YR' },
  { name: 'Introduction to Containers: Docker, Kubernetes and OpenShift', issuer: 'IBM · 2024', href: 'https://coursera.org/verify/Y5K83FQKDYCW' },
  { name: 'Django Application Development with SQL and Databases', issuer: 'IBM · 2023', href: 'https://coursera.org/verify/NWKP9P2BLAUS' },
  { name: 'Node.js — The Complete Guide', issuer: 'Udemy · 2023', href: 'https://ude.my/UC-c96779ac-f33e-4ab8-b6ab-17c8f1f75554' },
];

export default function About() {
  return <div className="container">
    <Seo title="About & experience" description="Meet Data Bassey, a Lagos-based senior software engineer with experience across fintech, banking, insurance, enterprise applications, and engineering leadership." />
    <section className="page-intro about-intro"><div><p className="eyebrow">About / Data Bassey</p><h1>Thoughtful systems.<br /><span className="serif">Shared progress.</span></h1><p>I’m Data, a senior software engineer based in Lagos with 6+ years of experience across web applications and PWAs. My fintech work includes facial-recognition KYC, bank-transfer workflows, wallet and card interfaces, merchant dashboards, and transaction operations. I combine frontend architecture, full-stack delivery, and technical leadership.</p><div className="actions"><Link className="button secondary" to="/resume">Download resume<ArrowDown size={18} aria-hidden="true" /></Link><a className="text-link" href={contact.linkedin} target="_blank" rel="noreferrer">LinkedIn<ArrowUpRight size={17} aria-hidden="true" /><span className="sr-only"> (opens in a new tab)</span></a></div></div><img className="about-portrait" src="/images/new.png" alt="Data Bassey" width="320" height="320" /></section>
    <section className="experience-section" id="experience"><div className="section-heading"><div><p className="eyebrow">01 / Career history</p><h2>Experience,<br /><span className="serif">with ownership.</span></h2></div><p className="section-aside">From small-business websites to enterprise workflows and engineering teams.</p></div><ol className="experience-list">{experience.map(item => <li key={item.company}><p className="experience-period">{item.period}</p><div><h3>{item.company}</h3><p className="experience-role">{item.role}</p><p>{item.detail}</p>{item.note && <p className="experience-note">{item.note}</p>}{item.project && <Link className="text-link" to={`/work/${item.project}`}>Explore related work<ArrowUpRight size={17} aria-hidden="true" /></Link>}</div></li>)}</ol></section>
    <section className="section"><p className="eyebrow">02 / Working approach</p><h2>Make the decisions<br /><span className="serif">understandable.</span></h2><div className="approach-grid"><article><span className="eyebrow">Start with the workflow</span><h3>Understand the task.</h3><p>I work with product and engineering teams to clarify user needs, technical constraints, and the steps that matter in the application.</p></article><article><span className="eyebrow">Build clear boundaries</span><h3>Keep change manageable.</h3><p>Reusable components, deliberate API layers, and modular features help engineers work in parallel without unnecessary coupling.</p></article><article><span className="eyebrow">Share the reasoning</span><h3>Deliver as a team.</h3><p>I use code reviews, mentoring, testing, and documentation to make delivery more consistent and help other engineers contribute.</p></article></div></section>
    <section className="credentials section"><div><p className="eyebrow">03 / Education</p><h2>Foundations.</h2><article><h3>BSc Computer Science</h3><p>University of Abuja · 2022</p></article><article><h3>OND Computer Science</h3><p>Edo State Polytechnic · 2019</p></article></div><div><p className="eyebrow">04 / Selected courses</p><h2>Continued learning.</h2><ul className="course-list">{courses.map(course => <li key={course.name}><a href={course.href} target="_blank" rel="noreferrer"><span><strong>{course.name}</strong><span className="muted">{course.issuer}</span></span><ArrowUpRight size={18} aria-hidden="true" /><span className="sr-only">Verify course completion (opens in a new tab)</span></a></li>)}</ul><p className="small muted">Course completion certificates. Additional learning is listed in my resume.</p></div></section>
  </div>;
}
